# Generated by Django 5.1.2 on 2025-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
