# Generated by Django 5.1.2 on 2025-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0002_alter_partner_email_alter_partner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_excl_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
