# Generated by Django 5.1.2 on 2025-05-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0003_invoice_amount_excl_tax_invoice_tax_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
    ]
