# Generated by Django 5.1.2 on 2025-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0004_rename_due_date_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
