# Generated by Django 5.1.2 on 2025-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0005_partner_partner_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_deducted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
