# Generated by Django 5.1.2 on 2025-05-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0006_invoice_is_deducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_deducted',
        ),
        migrations.AddField(
            model_name='invoice',
            name='not_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
