# Generated by Django 5.1.2 on 2025-05-09 09:42

import apar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apar', '0007_remove_invoice_is_deducted_invoice_not_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='兩個大寫英文字母加上八個數字，例如：AB12345678', max_length=10, null=True, unique=True, validators=[apar.models.validate_invoice_number]),
        ),
    ]
